@startuml
skinparam style strictuml

actor User as user order 0
participant Facade as facade order 5
participant AccountManager as accountManager order 10
database Database as db order 15

user -> facade : login (username, password)
facade -> accountManager: login (username, password)
accountManager -> db : SELECT * FROM users WHERE ...
alt account does not exist
  db -> accountManager : NULL
  accountManager -> facade : undefined
  facade -> user : login KO
end 
db -> accountManager : { username, email, ... }
create participant Account order 7 
accountManager -> Account : new
accountManager -> facade : account
facade -> user : login OK


@enduml
